var items = {
    starters:[
        {
            itemname:'vegmanchuria',
            itemprice:900,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'Panner',
            itemprice:1300,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'Chilli chicken',
            itemprice:1800,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'chicken-lollipops',
            itemprice:2000,
            quantity:1,
            quantityUnits:'kg'
        }
    ],
    liquids:[
        {
            itemname:'sambar',
            itemprice:300,
            quantity:1,
            quantityUnits:'liter'
        },
        {
            itemname:'rasam',
            itemprice:250,
            quantity:1,
            quantityUnits:'liter'
        },
        {
            itemname:'curd-chutney',
            itemprice:400,
            quantity:1,
            quantityUnits:'liter'
        },
        {
            itemname:'Gumadikay-pulusu',
            itemprice:500,
            quantity:1,
            quantityUnits:'liter'
        }
    ],
    curries:[
        {
            itemname:'Tomato-dal',
            itemprice:300,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'Potato',
            itemprice:190,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'panner-curry',
            itemprice:1800,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'chicken',
            itemprice:1700,
            quantity:1,
            quantityUnits:'kg'
        },
    ],
    rice:[
        {
            itemname:'pulihora',
            itemprice:1200,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'biryani',
            itemprice:1900,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'tomato rice',
            itemprice:1200,
            quantity:1,
            quantityUnits:'kg'
        },
    ],
    bread:[
        {
            itemname:'roti',
            itemprice:200,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'nan',
            itemprice:500,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemname:'rumali',
            itemprice:600,
            quantity:1,
            quantityUnits:'kg'
        },
    ]
}