var students = [
    {
      firstname:"Praveen",
      lastname:"Gubbala",
      age:40,
      gender:"male"
    },
    {
      firstname:"Smrithi",
      lastname:"mandana",
      age:25,
      gender:'female'
    },
    {
      firstname:"mithali",
      lastname:"raj",
      age:39,
      gender:'female'
    },
    {
      firstname:"Rohit",
      lastname:"Sharma",
      age:35,
      gender:'male'
    },
    {
      firstname:"Sachin",
      lastname:"Tendulkar",
      age:50,
      gender:'male'
    },
    {
      firstname:"dasu",
      lastname:"raj",
      age:39,
      gender:'male'
    },
    {
      firstname:"Anushka",
      lastname:"Sharma",
      age:25,
      gender:'female'
    },
    {
      firstname:"Krithi",
      lastname:"Shetty",
      age:20,
      gender:'female'
    },
]